app:
  theme: "default"
  verify_version: true
  emoji: false
  terminal_colorful: false
  run_time_app: 1
  monitor_to_use: 1
  captcha: false
  speed: "normal"
  multi_account:
    enable: false
    window_title: "bombcrypto"
    window_fullscreen: false

time_intervals:
  send_heroes_for_work: [30, 35]
  refresh_heroes_positions: [3, 4]

chests:
  values:
    chest_01: 0.01425
    chest_02: 0.03250
    chest_03: 0.16250
    chest_04: 0.32500

threshold:
  default: 0.7
  error_message: 0.7
  back_button: 0.9
  work_button: 0.9
  heroes_green_bar: 0.9
  heroes_full_bar: 0.9
  heroes_send_all: 0.9
  heroes_rest_all: 0.9
  chest: 0.65
  jail: 0.8
  auth_input: 0.9

heroes:
  mode: "green"
  list:
    scroll_attempts: 3

offsets:
  work_button_green: [120, 140] # [min value, max value]
  work_button_full: [90, 110] # [min value, max value]

metamask:
  enable: false
  password: ""

auth:
  enable: false
  username: ""
  password: ""

services:
  telegram: false

log:
  save_to_file: false
  debug: false
